cloud:
  aws:
    credentials:
      access-key: AKIA4YPMUJT7LBDDOQEK
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: yoga-heartbeat-s3


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
