cloud:
  aws:
    credentials:
      access-key: AKIARM3NVBBDTG2BCVEA
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: yoga-heartbeat


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
